import { Character, ResultsInfo } from '~Api/types'

export enum ActionType {
  COMPARATOR_CHARACTER_FETCH_FAILED = 'COMPARATOR_CHARACTER_FETCH_FAILED',
  COMPARATOR_CHARACTER_SELECTED_FETCH = 'COMPARATOR_CHARACTER_FETCH_FAILED',
  COMPARATOR_CHARACTER_SELECTED_SUCCESS = 'COMPARATOR_CHARACTER_SELECTED_SUCCESS',

  COMPARATOR_CHARACTER_SELECTED_POST_FAILED = 'COMPARATOR_CHARACTER_SELECTED_SEND_FAILED',
  COMPARATOR_CHARACTER_SELECTED_POST = 'COMPARATOR_CHARACTER_SELECTED_SEND',
  COMPARATOR_CHARACTER_SELECTED_POST_SUCCESS = 'COMPARATOR_CHARACTER_SELECTED_SEND_SUCCESS',

  COMPARATOR_CHARACTER_SELECTED_DEL_FAILED = 'COMPARATOR_CHARACTER_UNSELECT_SEND_FAILED',
  COMPARATOR_CHARACTER_SELECTED_DEL = 'COMPARATOR_CHARACTER_UNSELECT',
  COMPARATOR_CHARACTER_SELECTED_DEL_SUCCESS = 'COMPARATOR_CHARACTER_UNSELECT_SUCCESS',
}


export interface ResponseType {
  criticalError?: boolean
  error?: boolean
  payload: ResultsInfo<Character>
}

