export const CHARACTER_LIST_FAILED = 'CHARACTER_LIST_FAILED'
export const CHARACTER_LIST_FETCH = 'CHARACTER_LIST_FETCH'
export const CHARACTER_LIST_SEARCH = 'CHARACTER_LIST_SEARCH'
export const CHARACTER_LIST_SUCCEEDED = 'CHARACTER_LIST_SUCCEEDED'
