export const EPISODE_LIST_FAILED = 'EPISODE_LIST_FAILED'
export const EPISODE_LIST_FETCH = 'EPISODE_LIST_FETCH'
export const EPISODE_LIST_SEARCH = 'EPISODE_LIST_SEARCH'
export const EPISODE_LIST_SUCCEEDED = 'EPISODE_LIST_SUCCEEDED'
